### PR TITLE
Enable incremental TypeScript builds

### PR DESCRIPTION
**Pull request by vogelsgesang**
Cuts the time of `npm run compile` from 9 seconds to 3 seconds

### CODE REVIEW

**Review by jfirebaugh — COMMENTED** [review]
I'm mildly opposed to this. Every time I've tried to use incremental mode, I've ended up needing to turn it off because of weird bugs that lead to miscompilation or hard-to-debug behavior. It just doesn't seem to be a reliable feature. Plus it's not supported by rules_js, which we should be migrating to anyway.

**Comment by cameron-martin** [comment]
> I'm mildly opposed to this. Every time I've tried to use incremental mode, I've ended up needing to turn it off because of weird bugs that lead to miscompilation or hard-to-debug behavior. It just doesn't seem to be a reliable feature. Plus it's not supported by rules_js, which we should be migrating to anyway.

If there's known correctness issues then I'd also be in favour of not enabling this for the sake of 6 seconds.

**Comment by vogelsgesang** [comment]
Interesting... I never saw incremental build issues on any of my other Typescript projects. But given this does not align with the goals around `rules_js`, I agree we shouldn't merge it

On a related note: Are there reasons why the `strict` setting is not enabled in the `tsconfig.json`? I noticed a lot of issues diagnosed in particular by `strictNullChecks`. Would you welcome a change which enables `strict` type checking?

**Comment by jfirebaugh** [comment]
I would love a change to enable `strict`!

**Pull request closed without merging**
