### PR TITLE
Fix for file paths on Windows

### PR DESCRIPTION
**Pull request by jblanchet**
- Account for extra colon in Windows file path

Fixes [#65](https://github.com/bazelbuild/vscode-bazel/issues/65)

### CODE REVIEW

**Comment by allevato** [comment]
Thanks! This looks like a reasonable way to handle it. Can you please sign the CLA and comment on the PR once done?

**Comment by jblanchet** [comment]
Thanks @allevato, I did this through work so just need to acquire a sign off before signing the CLA.

**Comment by allevato** [comment]
Friendly ping—it would be great to get this into the next release. Were you able to sort out the CLA concerns with your employer?

**Comment by jblanchet** [comment]
Okay, I just got approval and signed for the company half of the CLA.

**Comment by allevato** [comment]
Thanks! It looks like corporate CAs may take a little bit more time to manually approve (as opposed to individual, which is instant), so I'll keep checking and flip the flag when it clears.

**Comment by jblanchet** [comment]
Looks like the CLA was rejected because I signed it and I'm not an executive (despite having executive approval). I'll try to get this bit sorted now.

**Comment by jblanchet** [comment]
Hi, @allevato , it seems that the company CLA has finally been signed. Only took a month and a half :)

**Comment by allevato** [comment]
Verified; thanks!

**Pull request merged**
