### PR TITLE
Document release process

### PR DESCRIPTION
**Pull request by jfirebaugh**
Adds instructions handed down to me via email to the repository.

### CODE REVIEW

**Review by coeuvre — APPROVED** [review]
Thanks!

**Comment by cameron-martin** [comment]
Would you be open to automating this? I've started using release please recently and it seems to work very well. The only slight change is using the conventional commits format, but I find this is quite lightweight.

**Comment by jfirebaugh** [comment]
Automation would be great!

**Comment by cameron-martin** [comment]
I've opened a PR here for this: #336

**Pull request merged**
