### PR TITLE
Add support for relative target completion

### PR DESCRIPTION
**Pull request by kon72**
This change enables the target completion to work with relative label starting with colon.

Depends on #305

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Thanks! I took the liberty of rebasing this on current master after merging #305. Do you think this and #307 are ready for review?

**Comment by kon72** [comment]
HI @jfirebaugh,

Thanks for the rebasing! I think this change is good to go.

For #307, I'm wondering if it may introduce some performance degradation, so I will do some more investigation and add an option for users to opt out of external rule completion.

**Review by jfirebaugh — APPROVED** [review]
Thank you! Out of curiosity, are you familiar with testing VS Code extensions? (I've never done it before.) Code completion seems like the sort of thing that would be nice to have tests around. No worries if not!

**Comment by cpsauer** [comment]
@kon72, thanks for working on these!

**Pull request merged**
